Revert "Revert "Pull WG on WD for now""
Error: 1146 Table 'wikidatawiki.wikigrok_questions' doesn't exist (10.64.32.28)


This reverts commit de4462360c5f8b75b7245aa01a9b693f7a497aa6.

Change-Id: Ie7b7e9ecfae9e11af3d168b91089dd9b84117643