Update patch set 1
Patch Set 1:

Apparently causes checkoutMediaWiki to die with:

 Fatal error: Class undefined: MWWikiversions in
/srv/mediawiki-staging/multiversion/updateBranchPointers on line 26

https://gerrit.wikimedia.org/r/#/c/271035/

Patch-set: 1
Reviewer: Hashar <24@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Verified=0