Revert "Use new TLS port for eventgate-analytics"
This reverts commit 9b9cadec7e5df1afba14db6a67704be2217c87fc.

Reason for revert: Event though a test of this worked fine on mwdebug1001, I am seeing lots of errors about failed POSTs.

BadRequestError: request aborted\n    at IncomingMessage.onAborted (/srv/service/node_modules/raw-body/index.js:231:10)\n    at IncomingMessage.emit (events.js:189:13)\n    at abortIncoming (_http_server.js:449:9)\n    at socketOnClose (_http_server.js:442:3)\n    at Socket.emit (events.js:194:15)\n    at TCP._handle.close (net.js:600:12)",


upstream connect error or disconnect/reset before headers. reset reason: connection termination

Change-Id: Id03e66e1c6789afe59f8d2e09b0d355ce50a1829