Update patch set 10
Patch Set 10:

That seems to be the cause of exceptions on the beta cluster such as :

Fatal error: Uncaught exception 'LogicException' with message 'Missing stream uri, the stream can not be opened.' in /mnt/srv/mediawiki-staging/php-master/includes/debug/logger/monolog/LegacyHandler.php:113


Filled as T97138 and causing beta Jenkins jobs to fail cause none of the mwscript command works (exception being the testwiki for some reason).

Patch-set: 10
Reviewer: Hashar <24@e9e9afe9-4712-486d-8885-f54b72dd1951>
Label: Verified=0