Revert "group1 wikis to 1.29.0-wmf.9"
Fatal error: Call to undefined method Revision::getText() in
php-1.29.0-wmf.9/extensions/FlaggedRevs/backend/FlaggedRevision.php
on line 480

This reverts commit 69da212b4cb7143d8a165fc20e98067e16a35cb4.

Bug: T156310
Bug: T156356
Change-Id: I3ca3f191e1a542f54f7d5a2e275d612a29bf4935