Revert "Add namespace to euwiki"
Jon Harald Søby and me were getting error pages at https://eu.wikipedia.org/wiki/Txikipedia:Cyrtodactylus_collegalensis

 Error

 Our servers are currently under maintenance or experiencing a technical problem. Please try again in a few minutes.

 See the error message at the bottom of this page for more information.

 If you report this error to the Wikimedia System Administrators, please include the details below.

 Request from 31.217.6.179 via cp1066 cp1066, Varnish XID 753828330
 Error: 508, Loop Detected at Wed, 04 Apr 2018 13:20:46 GMT


This reverts commit 5679a24088c4c88bf967f1ee73c253db100cb8bb.

Change-Id: If9a4901c68402c83e1d599566d9a84201402ab09