Revert "all wikis to 1.29.0-wmf.2" (Fatal errors spike)
Fatal error: Call to undefined method ApiQueryContributions::isInGeneratorMode() in /srv/mediawiki/php-1.29.0-wmf.2/extensions/ORES/includes/ApiHooks.php on line 172

This reverts commit f3c452f1d5d28328c66a98ecf63294c08c9e3382.

Change-Id: I86af2eebe9349dee8a48321823d28049df730acf