Update patch set 2
Patch Set 2:

Causes the following in production when calling updateWikiversions:
  Fatal error: Call to undefined function updateSymlink() in /srv/mediawiki-staging/multiversion/updateBranchPointers on line 41

Patch-set: 2