multiversion: updateBranchPointers miss a require
The script multiversion/updateBranchPointers fails when called from
checkoutMediaWiki with:

Fatal error: Class undefined: MWWikiversions in
/srv/mediawiki-staging/multiversion/updateBranchPointers on line 26

Seems to be due to d052abdd which introduced a call to:

   MWWikiversions::getAvailableBranchDirs()

require_once MWWikiversions.

Change-Id: I9c82c0c6f5961534ae640c0fccd3fad620e0cc1a