Revert "Flow settings: wmg -> wg migration, part 2"
Error: 1146 Table 'mediawikiwiki.flow_workflow' doesn't exist (10.64.16.18)

This reverts commit 496c8c6915f3661e6cacb16827c85367dbda680a.

Change-Id: Idaad5d91997951c87d2818f783dc6baa0b3796d1