Revert "Updating interwiki cache"
Scap fails with:

AttributeError: 'Namespace' object has no attribute 'force'
18:08:05 update-interwiki-cache failed: <AttributeError> 'Namespace' object has no attribute 'force'

This reverts commit 758302c11d181ca167bff0500a0ab2a65018f110.

Change-Id: Iec68712360142e5686612084037de335722200f9