Revert "cirrussearch: return traffic to all DCs"
This reverts commit 2983f0b96f7c5fd90243b5d7291cfb468cd14031.

Reason for revert: Test searches fail with:

RuntimeException: Missing replica <local>, have <eqiad,codfw,cloudelastic>

Plausibly the two variables here are set backwards, need to review
where the config is used and update the test suite to ensure it
is always configured appropriately.

Change-Id: I360fd2e058e681a9d94556c71cca562fdc8272a0